/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package junit.learning

import org.junit.jupiter.api.*
import org.junit.jupiter.api.Assertions.assertNotNull


class AppTest {

    @BeforeAll
    fun setup() {
        println("AppTest.setup")
    }

    @BeforeEach
    fun setUpThis() {
        println("AppTest.setUpThis")
    }


    @Tag("DEV")
    @Test
    fun testCalcOne() {
        println("AppTest.testCalcOne")
        Assertions.assertEquals(4, Calculator.add())
    }

    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
