/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package junit.learning

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test


class CalculatorTest {
    @Test
    fun `1 + 1 = 2`() {
        val calculator = Calculator()
        assertEquals(2, calculator.add(1, 1), "1 + 1 should equal 2")
    }
}
